@startuml design

' Executables
class client_main as "client_main.cpp"
class server_main as "server_main.cpp"

' Chat
class chat_core as "chat_core.cpp"
class msg_switch as "msg_switch.cpp"
class client_handler as "client_handler.cpp"

' Asymmetric Keygen
class key_gen as "key_gen.cpp"

' GUI
class main_window as "main_window.cpp"

''' Client GUI
client_main --> chat_core
chat_core --> key_gen
client_main --> main_window

''' Server
server_main --> client_handler
server_main --> msg_switch
client_handler --|> msg_switch : forwards messages

@enduml
