#ifndef MAIN_WINDOW_H
#define MAIN_WINDOW_H

#include <memory>

// Auto-generated by Qt's UI compiler
#include "ui_main_window.h"

#include "types.h"
#include "client_endpoint.h"


class MainWindow : public QMainWindow {
public:
    MainWindow();
    
    void initializeClientEndpoint(const ClientStartupInfo &);

protected:
    bool eventFilter(QObject *, QEvent *) override;

private:
    Ui_MainWindow *m_ui;
    std::unique_ptr<ClientEndpoint> m_ClientEndpointPtr;

private slots:
    void on_sendButton_clicked();
};

#endif // MAIN_WINDOW_H
