#ifndef MAIN_WINDOW_H
#define MAIN_WINDOW_H

#include <memory>

// Auto-generated by Qt's UI compiler
#include "ui_main_window.h"

#include "client_endpoint.h"


class MainWindow : public QMainWindow {
public:
    MainWindow();
    
    void initializeClientEndpoint();

private:
    Ui_MainWindow *m_ui;
    std::unique_ptr<ClientEndpoint> m_ClientEndpointPtr;

private slots:
    void on_sendButton_clicked();
    bool eventFilter(QObject *obj, QEvent *event) override;
};

#endif // MAIN_WINDOW_H
