#ifndef STARTUP_FORM_H
#define STARTUP_FORM_H

#include <QtGui/QCloseEvent>

// Auto-generated by Qt's UI compiler
#include "ui_startup_form.h"


class StartupForm : public QWidget {
    Q_OBJECT

public:
    StartupForm();

Q_SIGNALS:
    void formClosed();

protected:
    void closeEvent(QCloseEvent *event) override;

private:
    Ui_StartupForm *m_ui;
};

#endif // STARTUP_FORM_H
