#ifndef STARTUP_FORM_H
#define STARTUP_FORM_H

#include <QtGui/QCloseEvent>

// Auto-generated by Qt's UI compiler
#include "ui_startup_form.h"

#include "types.h"


class StartupForm : public QWidget {
    Q_OBJECT

public:
    StartupForm();

    const ClientStartupInfo &getClientStartupInfo() const {
        return m_clientStartupInfo;
    }

Q_SIGNALS:
    void formClosed();

protected:
    void closeEvent(QCloseEvent *) override;
    bool eventFilter(QObject *, QEvent *) override;

private:
    Ui_StartupForm *m_ui;
    ClientStartupInfo m_clientStartupInfo;

private slots:
    void on_connectButton_clicked();
};

#endif // STARTUP_FORM_H
